% baza faktów
%ja-rodzice
rodzenstwo(michal,magdalena).
rodzic(krzysztof,michal).
rodzic(krzysztof,magdalena).
rodzenstwo(krzysztof,izabela).
rodzenstwo(krzysztof,grazyna).
rodzic(barbara,michal).
rodzic(barbara,magdalena).
rodzenstwo(barbara,tadeusz).
malzenstwo(barbara,krzysztof).
% tata-rodzice
rodzic(teresa,krzysztof).
rodzic(eugeniusz,krzysztof).
malzenstwo(teresa,eugeniusz).
% mama-rodzice
rodzic(stanislawa,barbara).
rodzic(czeslaw,barbara).
malzenstwo(stanislawa,czeslaw).
% babcia_tata-rodzice
rodzic(anna,teresa).
rodzic(tomasz,teresa).
malzenstwo(anna,tomasz).
% dziadek_tata-rodzice
rodzic(lucja,eugeniusz).
rodzic(jakub,eugeniusz).
malzenstwo(lucja,jakub).
% babcia_mama-rodzice
rodzic(julia,stanislawa).
rodzic(antoni,stanislawa).
malzenstwo(julia,antoni).
% dziadek_mama-rodzice
rodzic(alicja,czeslaw).
rodzic(adam,czeslaw).
malzenstwo(alicja,adam).
% kuzyni/wujek/ciocia
rodzenstwo(grzegorz,krystian).
rodzic(izabela,grzegorz).
rodzic(izabela,krystian).
rodzic(miroslaw,grzegorz).
rodzic(miroslaw,krystian).
malzenstwo(izabela,miroslaw).
rodzic(teresa,izabela).
rodzic(eugeniusz,izabela).

rodzenstwo(paulina,karolina).
rodzic(grazyna,paulina).
rodzic(grazyna,karolina).
rodzic(lukasz,paulina).
rodzic(lukasz,karolina).
malzenstwo(grazyna,lukasz).
rodzic(teresa,grazyna).
rodzic(eugeniusz,grazyna).

rodzenstwo(joanna,marek).
rodzic(tadeusz,marek).
rodzic(tadeusz,joanna).
rodzic(zofia,marek).
rodzic(zofia,joanna).
malzenstwo(zofia,tadeusz).
rodzic(stanislawa,tadeusz).
rodzic(czeslaw,tadeusz).
% plec
kobieta(magdalena).
kobieta(julia).
kobieta(barbara).
kobieta(teresa).
kobieta(stanislawa).
kobieta(anna).
kobieta(lucja).
kobieta(joanna).
kobieta(alicja).
kobieta(grazyna).
kobieta(izabela).
kobieta(paulina).
kobieta(karolina).
kobieta(zofia).
mezczyzna(michal).
mezczyzna(krzysztof).
mezczyzna(eugeniusz).
mezczyzna(czeslaw).
mezczyzna(tomasz).
mezczyzna(antoni).
mezczyzna(jakub).
mezczyzna(adam).
mezczyzna(tadeusz).
mezczyzna(marek).
mezczyzna(grzegorz).
mezczyzna(krystian).
mezczyzna(miroslaw).
mezczyzna(lukasz).
%rok urodzenia
rokUrodzenia(stanislawa,1940).
rokUrodzenia(czeslaw,1942).
rokUrodzenia(teresa,1944).
rokUrodzenia(eugeniusz,1946).
rokUrodzenia(tadeusz,1970).
rokUrodzenia(zofia,1972).
rokUrodzenia(barbara,1973).
rokUrodzenia(krzysztof,1969).
rokUrodzenia(lukasz,1971).
rokUrodzenia(grazyna,1988).
rokUrodzenia(izabela,1960).
rokUrodzenia(miroslaw,1962).
rokUrodzenia(marek,2002).
rokUrodzenia(joanna,2000).
rokUrodzenia(michal,2001).
rokUrodzenia(magdalena,1998).
rokUrodzenia(paulina,2002).
rokUrodzenia(karolina,2014).
rokUrodzenia(grzegorz,2000).
rokUrodzenia(krystian,1995).
rokUrodzenia(julia,1920).
rokUrodzenia(antoni,1918).
rokUrodzenia(alicja,1921).
rokUrodzenia(adam,1915).
rokUrodzenia(anna,1921).
rokUrodzenia(tomasz,1920).
rokUrodzenia(lucja,1914).
rokUrodzenia(jakub,1910).
% zawod
zawod(stanislawa,sprzataczka).
zawod(czeslaw,maszynista).
zawod(teresa,rolnik).
zawod(eugeniusz,rolnik).
zawod(tadeusz,maszynista).
zawod(zofia,rolnik).
zawod(barbara,celnik).
zawod(krzysztof,elektronik).
zawod(lukasz,prawocnik_biurowy).
zawod(grazyna,pracownik_biurowy).
zawod(izabela, auczyciel).
zawod(miroslaw,kierowca).
zawod(marek,maszynista).
zawod(joanna,ksiegowa).
zawod(michal,student).
zawod(magdalena,nauczycielka).
zawod(paulina,student).
zawod(karolina,uczen).
zawod(grzegorz,kucharz).
zawod(krystian,kierowca).
zawod(julia,rolnik).
zawod(antoni,rolnik).
zawod(alicja,rolnik).
zawod(adam,rolnik).
zawod(anna,rolnik).
zawod(tomasz,rolnik).
zawod(lucja,rolnik).
zawod(jakub,rolnik).
%szkola
szkola(stanislawa,podstawowa).
szkola(czeslaw,podstawowa).
szkola(teresa,podstawowa).
szkola(eugeniusz,podstawowa).
szkola(tadeusz,technikum).
szkola(zofia,technikum).
szkola(barbara,technikum).
szkola(krzysztof,technikum).
szkola(lukasz,uniwersytet).
szkola(grazyna,uniwersytet).
szkola(izabela,uniwersytet).
szkola(miroslaw,liceum).
szkola(marek,technikum).
szkola(joanna,uniwersytet).
szkola(michal,technikum).
szkola(magdalena,uniwersytet).
szkola(paulina,liceum).
szkola(karolina,podstawowa).
szkola(grzegorz,liceum).
szkola(krystian,liceum).
szkola(julia,podstawowa).
szkola(antoni,podstawowa).
szkola(alicja,podstawowa).
szkola(adam,podstawowa).
szkola(anna,podstawowa).
szkola(tomasz,podstawowa).
szkola(lucja,podstawowa).
szkola(jakub,podstawowa).
% cechy
choreOczy(eugeniusz).
umieRysowac(barbara).
dobrzeGotuje(stanislawa).
dobrzeGotuje(teresa).
pracowita(teresa).
pracowita(stanislawa).
pracowity(czeslaw).
pracowity(krzysztof).
pracowita(barbara).
pracowity(tedeusz).
pracowity(lukasz).
pracowita(izabela).
% prawo jazdy
prawo_jazdy(czeslaw).
prawo_jazdy(eugeniusz).
prawo_jazdy(tadeusz).
prawo_jazdy(zofia).
prawo_jazdy(barbara).
prawo_jazdy(krzysztof).
prawo_jazdy(lukasz).
prawo_jazdy(grazyna).
prawo_jazdy(izabela).
prawo_jazdy(miroslaw).
prawo_jazdy(marek).
prawo_jazdy(joanna).
prawo_jazdy(michal).
prawo_jazdy(magdalena).
prawo_jazdy(paulina).
prawo_jazdy(grzegorz).
prawo_jazdy(krystian).
% pojazd
pojazd(czeslaw,samochod).
pojazd(tadeusz,samochod).
pojazd(zofia,samochod).
pojazd(barbara,samochod).
pojazd(krzysztof,samochod).
pojazd(lukasz,samochod).
pojazd(grazyna,samochod).
pojazd(izabela,samochod).
pojazd(miroslaw,samochod).
pojazd(magdalena,samochod).
pojazd(grzegorz,samochod).
pojazd(krystian,samochod).
% baza predykatow
% relacje rodzinne
matka(X,Y):-rodzic(X,Y),kobieta(X).
ojciec(X,Y):-rodzic(X,Y),mezczyzna(X).
dziadkowie(X,Z):-rodzic(X,Y),rodzic(Y,Z).
dziadek(X,Z):-dziadkowie(X,Z),mezczyzna(X).
babcia(X,Z):-dziadkowie(X,Z),kobieta(X).
pradziadkowie(X,Z):-rodzic(X,Y),dziadkowie(Y,Z).
pradziadek(X,Z):-pradziadkowie(X,Z),mezczyzna(X).
prababcia(X,Z):-pradziadkowie(X,Z),kobieta(X).
syn(X,Y):-rodzic(Y,X),mezczyzna(X).
corka(X,Y):-rodzic(Y,X),kobieta(X).
wnuk(X,Y):-dziadkowie(Y,X),mezczyzna(X).
wnuczka(X,Y):-dziadkowie(Y,X),kobieta(X).
prawnuczek(X,Y):-pradziadkowie(Y,X),mezczyzna(X).
prawnuczka(X,Y):-pradziadkowie(Y,X),kobieta(X).
maz(X,Y):-malzenstwo(Y,X),mezczyzna(X).
zona(X,Y):-malzenstwo(X,Y),kobieta(X).
ciotka(X,Y):-kobieta(X),rodzic(Z,Y),(rodzenstwo(X,Z);rodzenstwo(Z,X)).
wujek(X,Y):-mezczyzna(X),rodzic(Z,Y),(rodzenstwo(X,Z);rodzenstwo(Z,X)).
brat(X,Y):-(rodzenstwo(X,Y);rodzenstwo(Y,X)),mezczyzna(X).
siostra(X,Y):-(rodzenstwo(X,Y);rodzenstwo(Y,X)),kobieta(X).
szwagier(X,Z):-(brat(X,Y),(maz(Z,Y);zona(Y,Z)), mezczyzna(X));(brat(Z,Y),(zona(Y,X);maz(Y,X)),mezczyzna(X)).
szwagierka(X,Z):-(siostra(X,Y),(maz(Z,Y);zona(Z,Y)),kobieta(X));(siostra(Z,Y),(zona(Y,X);maz(Y,X)),kobieta(X)).
kuzyn(X,Y):-syn(X,W),((rodzenstwo(W,K);rodzenstwo(K,W)),rodzic(K,Y)).
kuzynka(X,Y):-corka(X,W),((rodzenstwo(W,K);rodzenstwo(K,W)),rodzic(K,Y)).
% cechy
choreOczy(X):-rodzic(Y,X),choreOczy(Y),mezczyzna(X).
umieRysowac(X):-rodzic(Y,X),umieRysowac(Y),kobieta(X).
dobrzeGotuje(X):-rodzic(Y,X),dobrzeGotuje(Y),(pracowita(X);pracowity(X)).
mozeJezdzic(X) :-prawo_jazdy(X),(pojazd(X,_);(rodzic(Y,X),pojazd(Y,_))).
uczySie(X):-zawod(X,student);zawod(X,uczen).
wyksztalcony(X):-szkola(X,uniwersytet);zawod(X,student).